version: '3.3'
services:
  db:
    image: mariadb
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
      MYSQL_DATABASE: mpire_vinpro
      MYSQL_USER: mpire_vinpro
      MYSQL_PASSWORD: 123qwe
  php:
    image: sethsandaru/nginx-php-7-2
    container_name: sethphat-counter
    ports:
      - 82:80
    volumes:
      - ./:/var/www/html
    links:
      - db:db
#      - redis:redis
#  redis:
#    image: redis